### ISSUE TITLE
Issue with Redis-Cache & Cache Invalidation / Update

### ISSUE THREAD

**Issue by cookiesowns** [tillkruss/redis-cache#58] opened 2017-03-04 02:14 UTC
Hi,

Currently we're running redis-cache in production. It appears there is sometimes an edge-case once our redis store has many keys ( 7mill+ ) where once a key is set, eg `user_meta` the key even when updated via update_user_meta, it is never updated in the redis-cache. This is no bueno as even when the user_meta is changed in DB... the redis-cache continues serving stale values.

It's only when we forcefully DELETE the key where everything works fine. However this only happens when the redis DB has been operational for a while, and we slam it with requests to get & update_user_meta.

It seems there is some logic when updating user_meta where, if the value isn't updated in the database ( values are the same ), the redis cache is not invalidated, or updated.

**Comment by tillkruss** [comment] 2017-03-04 02:27
Can you narrow down the code that's setting/reading the user meta that's stale?

**Comment by kevinlisota** [comment] 2017-05-13 23:49
@tillkruss We're actually seeing something similar here. Our cache grows to about 3.5M keys when it's been running for a couple of days.

On a "fresh" cache, everything works as expected. But at some point, the cache begins returning stale results, even though the DB has been updated with different values.

The most obvious place we see it is on the admin console when setting options or meta values. I've tracked a few different code paths in the admin console, and it is simple calls to update_option or update_post_meta that somehow aren't replacing the Redis key.

In a couple cases, I could see via Query Monitor that two plugins were trying to update_option on every pageload. Those plugins would check the value of a particular option, then update it if needed, but the DB saves were never being replaced in Redis, so it kept trying over and over.

I'm trying to do more research here to pinpoint it, but it is not plugin related, as I've seen it across a variety of plugins using update_option and update_post_meta. (and add_post_meta/delete_post_meta)

Could this be related to TTL by chance? We do not have anything set there.

**Comment by tillkruss** [comment] 2017-05-14 00:05
I assume the outdated cache data is plugin/theme related. In that case your issues is most likely caused by the theme or plugin(s) itself, because they don't handle their cached data properly. _Invalidating cache is one of the hardest things in computer science._

You can set a MaxTTL for all keys to keep the outdated cache data at bay, but it doesn't solve the problem of having outdated data.

I personally prefer solving it by updating the cache when the data changes, because I dislike stale cache data.

**Comment by kevinlisota** [comment] 2017-05-14 00:38
Actually, the update_option issue I'm seeing could be related to how wordpress stores, caches and loads the alloptions array. Related bug in trac here:

https://core.trac.wordpress.org/ticket/31245

I'm looking at multiple plugins, and they are simply calling functions like update_option, delete_option, add_option and relying on core to do the wp_cache_set/wp_cache_delete functions which puts stuff into the object cache and removes or updates it as needed. For whatever reason, those updates propagate to the DB, but not the cache.

These functions work fine without an object cache and write to the DB properly, and based on the cache_get/cache_delete functions in core, they should be handled correctly by an object cache, but are not. I have run these plugins for years on memcached object cache, and just switched to Redis last week, and began seeing this.

Here is a simple example
http://foliovision.com/seo-tools/wordpress/plugins/fv-top-level-categories

You'll see how they get_option, check for the presence of a key and flush rewrite rules if the key isn't present. In our case, the cached version of the option gets stuck and the flush rewrite rules runs on every pageload.

**Comment by tillkruss** [comment] 2017-05-14 01:05
Interesting. If you find anything, please feel free to make a PR.

One thing I forgot to mention was, you can always ignore certain cache groups that are troubling you (at least until WordPress fixes their stuff).

**Comment by kevinlisota** [comment] 2017-05-16 07:22
Here is a good workaround on the race condition on `alloptions`

https://github.com/Automattic/vip-mu-plugins-public/blob/master/misc.php#L66-L83

My suggestion, whether for Redis or other object cache, is to point users to this workaround until the issue in core is fixed. Otherwise you get strange/stale results when working with any autoloaded option, of which many can be quite important.

**Comment by tillkruss** [comment] 2017-05-16 14:01
Great! It probably makes sense to add this to this plugin until WordPress fixes the bug, eh?

**Comment by vincent-lu** [comment] 2017-07-03 22:54
Hi @tillkruss and @kevinlisota, can you guys help me get started to implement this fix before WP core team decides on a solution?

@kevinlisota Reading https://core.trac.wordpress.org/ticket/31245 led me to https://wordpress.org/plugins/wp-lcache/ which seems to circumvent this issue. What object cache solution would you currently recommend for high traffic website?

**Comment by cookiesowns** [comment] 2017-07-03 23:08
@tillkruss For some reason I did not recieve notifications on the GH issue response....

That said, here's a ticket that I've opened with wordpress core.

https://core.trac.wordpress.org/ticket/40052

The issue isn't related to the theme, but rather how the core handles object caching with stale data. If the data is stale in the cache back end, but is correct in the DB ( due to a failed update to the cache store ) it will never update and will always return stale data.....

**Comment by kevinlisota** [comment] 2017-07-06 04:24
@cookiesowns I tried out lcache with all sorts of problems. The development team responded to me with this:

https://wordpress.org/support/topic/heavy-iops-and-database-use/

It looks good in concept, but it is not ready. We use Redis with this plugin with good success.

There is a known race condition with object caching, unrelated to the cache, but a problem with WP core that still needs fixing. You can see it when you make settings changes that may save in the database, but don't take effect on the site because of stale cache data, which can make it nearly impossible to configure a site.

The workaround I mentioned above is working for us at the moment. Here it is again:

https://github.com/Automattic/vip-mu-plugins-public/blob/master/misc.php#L66-L83

**Comment by vincent-lu** [comment] 2017-07-07 04:50
Hi @kevinlisota I see you around `lcache` and WP's forums as I'm chasing a solution to the same problem.

Is it correct that you guys currently use `tillkruss/redis-cache` as your object cache solution on production, the those lines added anywhere in the WP includes (themes, plugins, whatever) https://github.com/Automattic/vip-mu-plugins-public/blob/master/misc.php#L66-L83

Has `lcache` ever worked for you guys? See my problem with `lcache` seems to be similar to your experience https://github.com/lcache/wp-lcache/issues/137

Lastly, what about https://github.com/pantheon-systems/wp-redis, have you tried it?

Many thanks.

**Comment by tillkruss** [comment] 2017-07-07 21:36
Don't add the race condition fix in WordPress, put it in a MU-plugin.

**Comment by abdusfauzi** [comment] 2017-07-17 12:47
No wonder I kept on having issue with stale data. Thanks everyone :)

**Comment by bdtech** [comment] 2017-07-17 13:02
I have the max_ttl set at 10 minutes. Haven't seen this issue yet...

**Comment by abdusfauzi** [comment] 2018-04-20 11:05
@ottok possible to share the whole snippet? or mu-plugin file?

Thank you 😀

**Comment by tillkruss** [comment] 2018-04-20 15:16
@ottok: I'm open to a PR!

**Comment by partounian** [comment] 2018-10-21 03:44
@ottok please

**Comment by tillkruss** [comment] 2019-11-24 18:30
https://core.trac.wordpress.org/ticket/31245 was moved for 5.3.1 consideration.

**Comment by tillkruss** [comment] 2020-01-21 21:53
Fixed in WP 5.3.1

**Closed by tillkruss** 2020-01-21 21:53 UTC
Labels: bug, wontfix

**Comment by ottok** [comment] 2020-01-22 06:43
> @ottok possible to share the whole snippet? or mu-plugin file?
> 
> Thank you

Sorry @tillkruss, I didn't notice your follow-up question. Here is the whole snippet in context: https://github.com/Seravo/seravo-plugin/commit/6195003bc9caf18ae346c75898643f71172fe075

**Comment by tillkruss** [comment] 2020-01-22 16:04
No problem. WP core fixed it finally.
