### ISSUE TITLE
Plugin activation/deactivation not updating cache

### ISSUE THREAD

**Issue by ethanclevenger91** [tillkruss/redis-cache#137] opened 2019-12-04 20:25 UTC
Heyo - sometimes I activate or deactivate plugins and the change isn't reflected in the admin until I flush the cache. This can make debugging super difficult sometimes. Any idea what this might be about? Unfortunately, I don't have specific steps to replicate.

**Comment by tillkruss** [comment] 2019-12-04 21:10
Yes, the plugin doesn’t flush the cache without the user initiating it. Flushing the entire database upon activation might cause data loss. It could be added as an opt-in setting tho.

**Comment by ethanclevenger91** [comment] 2019-12-06 00:20
I mean, I'm not suggesting the whole database should be flushed. But if I activate/deactivate some plugin (not Redis Cache) while Redis Cache is active, it seems like the admin should reflect that change. Like, I can deactivate Query Monitor, but it still shows as active and I still get query monitor information in my admin bar. That doesn't seem right.

Granted I don't know a ton about Redis or how that works.

**Comment by tillkruss** [comment] 2019-12-06 01:18
Gotcha! Yes, that should not happen. Something must be off on your installation where the options aren’t cached properly.

**Comment by naxvog** [comment] 2019-12-09 13:47
This might be because of the selective cache flush issue. Does it still occur using version 1.5.5?

**Comment by ethanclevenger91** [comment] 2019-12-18 19:51
I'll get updated to 1.5.5 and let you know if the issue persists. In the meantime @tillkruss I can provide diagnostics:

```
Status: Connected
Redis Version: 4.0.10
Client: Predis (v1.1.1)
Drop-in: Valid
Ping: PONG
Redis Extension: Not Found
Predis Client: 1.1.1
PHP Version: 7.3.12
Multisite: No
Global Prefix: "wp_"
Blog Prefix: "wp_"
WP_REDIS_HOST: "collider.av2uq4.ng.0001.use1.cache.amazonaws.com"
WP_REDIS_PORT: 6379
WP_REDIS_DATABASE: 0
WP_CACHE_KEY_SALT: "collider_v2_03012019"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "blog_meta",
    "ludicrousdb"
]
Ignored Groups: [
    "counts",
    "plugins",
    "themes"
]
Unflushable Groups: []
Dropins: 
 - LudicrousDB (Database) v5.0.0 by JJJ & Friends
 - Redis Object Cache Drop-In v1.5.2 by Till Krüss
Plugins: 
 - ACF Repeater & Flexible Content Collapser v1.2.3 by Thomas Meyer (Active)
 - Ads.txt Manager v1.1 by 10up (Active)
 - Advanced Custom Fields PRO v5.8.7 by Elliot Condon (Active)
 - AMP v1.4.1 by AMP Project Contributors (Active)
 - Classic Editor v1.5 by WordPress Contributors (Active)
 - Collider v by Sterner Stuff Design (Active)
 - Complex TV Embed v1.3 by Anthony Rivera (Active)
 - Disable Search v1.7.1 by Scott Reilly (Active)
 - ElasticPress v3.2.6 by 10up (Active)
 - Envira Gallery v1.8.7.3 by Envira Gallery Team (Active)
 - Fastly v1.2.11 by  (Active)
 - Infinite Scroll v2.6.2 by Beaver6813, dirkhaim, Paul Irish, benbalter, Glenn Nelson (Active)
 - Query Monitor v3.4.0 by John Blackbourn (Inactive)
 - Redis Object Cache v1.5.2 by Till Krüss (Active)
 - Regenerate Thumbnails v3.1.2 by Alex Mills (Viper007Bond) (Active)
 - Rollbar v2.6.0 by Rollbar (Inactive)
 - User Switching v1.5.3 by John Blackbourn & contributors (Inactive)
 - Wordfence Security v7.4.1 by Wordfence (Inactive)
 - WP Crontrol v1.7.1 by John Blackbourn & crontributors (Inactive)
 - WP Migrate DB Pro v1.9.8 by Delicious Brains (Active)
 - WP Offload Media v2.3.1 by Delicious Brains (Active)
 - WP to Twitter v3.4.4 by Joseph C Dolson (Active)
 - WPtouch Pro v3.0.6 by BraveNewCode Inc. (Active)
 - Yoast SEO v12.5.1 by Team Yoast (Active)
 - Yoast SEO: News v12.2 by Team Yoast (Active)
```

**Comment by tillkruss** [comment] 2020-01-21 21:53
The option race condition issue was fixed in WP 5.3.1.

Is this still relevant?

**Closed** 2020-05-04 16:42 UTC

**Comment by kms54321** [comment] 2021-04-15 01:04
I have this same issue with the current version. I had supervisord installed on cloudways, which seemed have been the cause of the problem.

**Comment by kms54321** [comment] 2021-04-15 03:47
I cobbled together a snippet that seems to work okay. I still have to a refresh, but at least it works. I had to up priority to 9 to be sure.

add_action( 'activated_plugin', 'activated_plugin_example', 9, 2);
add_action( 'deactivated_plugin', 'activated_plugin_example', 9, 2);
function activated_plugin_example( $plugin, $network_activation ) {
    wp_cache_flush();
}
